### ISSUE TITLE
SkillCheck failed networking Packet handling

### ISSUE THREAD

**Issue by Luxley** [CottonMC/SkillCheck#18]
Hi! First time using github and reoporting an issue

im running a 1.14 server using 1.0.8 version of SkillCheck. 

its failing to display and remember my levels and consumes exp without giving the benefits/display of the level

[latest.log](https://github.com/CottonMC/SkillCheck/files/3205416/latest.log)

**Comment by LemmaEOF** [comment]
Ah, I see the issue here. It's some more siding issues. I'll get it patched up ASAP.

**Comment by Luxley** [comment]
Round 2!
@Boundarybreaker 

[latest.log](https://github.com/CottonMC/SkillCheck/files/3205554/latest.log)

**Comment by LemmaEOF** [comment]
This still says Skillcheck v1.0.8. Update to v1.0.9, which is in the Releases tab on the repo and *should* be on CurseForge by now.

**Comment by Luxley** [comment]
Ive already updated it to 1.0.9

**Comment by LemmaEOF** [comment]
The log isn't agreeing, is the issue. Try downloading the jar again? If it doesn't work, it might be an issue with the build.

**Comment by Luxley** [comment]
Same results

[latest(1).log](https://github.com/CottonMC/SkillCheck/files/3205580/latest.1.log)

**Comment by LemmaEOF** [comment]
Alright [try this build](https://dsc.cloud/b0undarybreaker/skillcheck-1.0.9-1.14.1.jar).

**Comment by Luxley** [comment]
Same results~

[latest.log](https://github.com/CottonMC/SkillCheck/files/3205613/latest.log)

**Comment by LemmaEOF** [comment]
It looks like it's happening because of Tweed this time, actually. SkillCheck is now officially fixed!

**Comment by Luxley** [comment]
So what should i do then? its still not workin on the server and tweed just crashes the server?

**Comment by LemmaEOF** [comment]
Now take it over to Tweed's github. SkillCheck no longer crashes.
