### ISSUE TITLE
Bundled crochet version causing crash on load

### ISSUE THREAD

**Issue by sargunv** [CottonMC/SkillCheck#2]
Before installing this mod, I had the version of Crochet bundled with Arcane Magic, which was working fine. After installing this mod, Fabric started loading the Crochet jar bundled with Skillcheck, which appears to be bad. Crash log: https://paste.ee/p/eTUoY

* Latest crochet jar from Curseforge: 
  * file: Crochet-1.0.2.jar
  * semver: 1.0.2
* Arcane Magic's crochet jar:
  * file: Crochet-1.0.2-1.jar
  * semver: 1.0.2-1
* Skillcheck's crochet jar: 
  * file: crochet-a203643485.jar
  * semver: 1.0.2-2

1.0.2 (fine) > 1.0.2-2 (broken) > 1.0.2-1 (fine)

**Comment by Pannoniae** [comment]
The mod crotchet isn't getting remapped correctly.

**Comment by sargunv** [comment]
Yes, that's clear from the crash log. The latest crochet works fine, but the version bundled with this mod's jar is bad. I assume it's some issue with jitpack. I recommend using the Curseforge maven for crochet instead of jitpack, that's what raphy uses: https://github.com/raphydaphy/ArcaneMagic/blob/master/build.gradle#L44

**Comment by LemmaEOF** [comment]
yeah, I'm gonna move to CFMaven.
