### ISSUE TITLE
SkillCheck or one of its included mods has an undeclared dependency on ModMenu

### ISSUE THREAD

**Issue by sargunv** [CottonMC/SkillCheck#20]
Crashes on load without ModMenu installed.

https://paste.ee/p/EGywv

**Comment by LemmaEOF** [comment]
Weird, SkillCheck's ModMenu code shouldn't be loaded if ModMenu isn't present. I'll see what's going on.

**Comment by LemmaEOF** [comment]
yep, it's just in the same SkillCheckClient code. I have no idea why, I thought I'd changed that. Fixing.
