### ISSUE TITLE
Thief's wall hanging conflicts with ladders

### ISSUE THREAD

**Issue by SPTX** [CottonMC/SkillCheck#22]
When you hold sneak on a ladder, in vanilla it makes it so that you don't automatically go down the ladder. The thief's skill activates with the same conditions and it makes the character move frantically instead of holding in place.

v1.1.2+1.14.3

**Comment by LemmaEOF** [comment]
Huh. I thought I'd added in a check for that. I'll take a look. This will also be a lot easier to fix once we've got the climbable API in Fabric.

**Comment by LemmaEOF** [comment]
Alright! I've got this fixed in dev for version 2.0. A beta release should be out soon!
